const eur=new Intl.NumberFormat('en-IE',{style:'currency',currency:'EUR',maximumFractionDigits:0});
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>n==null?'Unavailable':eur.format(n);
const signed=n=>n==null?'Unavailable':`${n<0?'(':''}${eur.format(Math.abs(n))}${n<0?')':''}`;
const label=s=>s.replace(/([A-Z])/g,' $1').replace(/^./,c=>c.toUpperCase());
const row=(name,value,total=false,note='')=>`<tr class="${total?'total':''}"><td>${esc(name)}${note?`<span class="cell-note">${esc(note)}</span>`:''}</td><td class="num">${typeof value==='number'?signed(value):esc(value??'Unavailable')}</td></tr>`;
const effect=e=>Object.entries(e||{}).map(([k,v])=>`${label(k)}: ${v==null?'—':signed(v)}`).join(' · ');

async function load(){
  const app=document.querySelector('#app');
  try{
    const response=await fetch('/submission.json',{cache:'no-store'});
    if(!response.ok) throw new Error(`Submission data returned ${response.status}`);
    const data=await response.json();
    document.body.dataset.view==='review'?renderReview(app,data):renderMain(app,data);
  }catch(error){app.innerHTML=`<p class="error">Could not load the case data: ${esc(error.message)}</p>`}
}

function schedulePanel(title,data){return `<article class="panel schedule"><h3>${esc(title)}</h3><table><tbody>${Object.entries(data).map(([k,v])=>row(label(k),v)).join('')}</tbody></table></article>`}
function evidenceCard(e){return `<article class="evidence-card"><div><span class="pill ${e.reliability}">${esc(e.reliability)}</span><span class="source-id">${esc(e.id)}</span></div><h3>${esc(e.title)}</h3><p>${esc(e.type)}</p><strong>${esc(e.locators[0])}</strong><ul>${e.keyFacts.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></article>`}
function decisionRows(decisions){return decisions.map(d=>`<tr data-search="${esc(`${d.id} ${d.question} ${d.answer}`.toLowerCase())}" data-confidence="${esc(d.confidence)}"><td>${esc(d.id)}</td><td><strong>${esc(d.question)}</strong><div class="evidence">${d.evidenceDetails?.map(x=>`${esc(x.sourceId||'')} ${esc(x.locator)}`).join('<br>')||d.evidence.map(esc).join(' · ')}</div></td><td class="decision-answer">${esc(d.answer)}</td><td><span class="pill ${d.confidence}">${esc(d.confidence)}</span><span class="cert-status">${d.certificationStatus==='pending_student_review'?'Student review pending':'Certified'}</span></td></tr>`).join('')}
function addDecisionFilters(){const search=document.querySelector('#decision-search'),confidence=document.querySelector('#confidence-filter');if(!search||!confidence)return;const filter=()=>document.querySelectorAll('#decision-table tbody tr').forEach(tr=>{const text=search.value.trim().toLowerCase();tr.hidden=!tr.dataset.search.includes(text)||(confidence.value!=='all'&&tr.dataset.confidence!==confidence.value)});search.addEventListener('input',filter);confidence.addEventListener('change',filter)}

function renderMain(app,d){
  const p=d.statements.profitAndLoss,c=d.statements.cashFlow,b=d.statements.balanceSheet;
  const ready=d.submissionReadiness.ready, certified=d.student.certificationStatus==='certified';
  const statusLabel=ready?'Submission ready':certified?'Certified · deployment pending':'Not submission-ready';
  const gateTitle=ready?'Student-certified final submission':'Student certification gate';
  const gateText=ready?`Certified by ${d.student.name} (${d.student.id}) on ${d.student.certifiedAt}. All published routes were verified.`:certified?'All 100 decisions are certified. Publication remains pending only until the deployed routes are verified.':'The financial reconstruction is complete, but publication remains blocked until the student ID and personal review are supplied.';
  app.innerHTML=`
    <section class="hero"><div><p class="eyebrow">Financial crime-scene reconstruction · Version 3</p><h1>Profitable core. Unreliable records. Immediate controls required.</h1><p class="lede">The evidence supports a provisional base-case profit of ${money(p.netProfit)} and closing cash of ${money(c.closingCash)}. Management's ${money(312000)} claim is unsupported.</p></div><aside class="verdict"><small>Board recommendation</small><strong>Continue under strict remediation</strong><p>${esc(d.boardRecommendation.warning)}</p></aside></section>
    <section class="gate" aria-label="Submission status"><div><span class="pill ${ready?'closed':'open'}">${esc(statusLabel)}</span><h2>${esc(gateTitle)}</h2><p>${esc(gateText)}</p></div>${d.submissionReadiness.blockingItems.length?`<ul>${d.submissionReadiness.blockingItems.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:`<p><strong>Certification:</strong> ${esc(d.student.certificationStatement)}</p>`}</section>
    <section class="metrics" aria-label="Key results"><article class="metric"><span>Corrected revenue</span><strong>${money(p.revenue)}</strong></article><article class="metric"><span>Base-case net profit</span><strong>${money(p.netProfit)}</strong></article><article class="metric"><span>Closing cash</span><strong>${money(c.closingCash)}</strong></article><article class="metric bad"><span>Total liabilities</span><strong>${money(b.liabilities.totalLiabilities)}</strong></article></section>

    <section class="section" id="statements"><div class="section-head"><div><p class="eyebrow">Financial statements</p><h2>Corrected base case</h2></div><p>Insurance remains unavailable. The disputed €9,000 inventory difference is not recognized as income.</p></div><div class="grid">
      <article class="panel"><h3>Profit and loss</h3><table>${row('Revenue',p.revenue)}${row('Physical materials',p.physicalMaterialsCogs)}${row('Direct event payroll',p.directEventPayroll)}${row('Damaged-stock write-off',p.damagedStockWriteOff)}${row('Gross profit',p.grossProfit,true)}${row('Sales payroll',p.salesPayroll)}${row('Office payroll',p.officePayroll)}${row('Rent',p.rent)}${row('Marketing',p.marketing)}${row('Software',p.software)}${row('Utilities',p.utilities)}${row('Repairs',p.repairs)}${row('Depreciation',p.depreciation)}${row('Bad debt',p.badDebtExpense)}${row('Legal provision',p.legalExpense)}${row('Insurance',p.insuranceExpense,false,'No evidence; no adjustment recorded')}${row('Operating profit',p.operatingProfit,true)}${row('Interest',p.interestExpense)}${row('Net profit',p.netProfit,true)}</table></article>
      <article class="panel"><h3>Balance sheet</h3><table>${row('Cash',b.assets.cash)}${row('Receivables',b.assets.receivables)}${row('Inventory',b.assets.inventory,false,'€9,000 physical-count conflict disclosed')}${row('PPE, net',b.assets.ppeNet)}${row('Total assets',b.assets.totalAssets,true)}${row('Supplier payables',-b.liabilities.supplierPayables)}${row('Payroll payable',-b.liabilities.payrollPayable)}${row('Customer deposits',-b.liabilities.customerDeposits)}${row('Interest payable',-b.liabilities.interestPayable)}${row('Legal provision',-b.liabilities.legalProvision)}${row('Bank loan',-b.liabilities.bankLoan)}${row('Total liabilities',-b.liabilities.totalLiabilities,true)}${row('Equity',-b.equity.closingEquity)}${row('Liabilities and equity',-b.totalLiabilitiesAndEquity,true)}</table></article>
      <article class="panel wide"><h3>Cash flow</h3><table><tbody>${row('Opening cash',c.openingCash)}${row('Customer receipts',c.customerReceipts)}${row('Supplier payments',c.supplierPayments)}${row('Payroll paid',c.payrollPaid)}${row('Rent, marketing, software, utilities and repairs',c.rentPaid+c.marketingPaid+c.softwarePaid+c.utilitiesPaid+c.repairsPaid)}${row('Interest paid',c.interestPaid)}${row('Net operating cash flow',c.netOperatingCashFlow,true)}${row('Equipment purchases',c.equipmentPurchases)}${row('Net investing cash flow',c.netInvestingCashFlow,true)}${row('New borrowing',c.newBorrowing)}${row('Principal repaid',c.principalRepaid)}${row('Owner distributions',c.ownerDistributions)}${row('Net financing cash flow',c.netFinancingCashFlow,true)}${row('Closing cash',c.closingCash,true)}</tbody></table></article>
    </div></section>

    <section class="section" id="schedules"><div class="section-head"><div><p class="eyebrow">Supporting schedules</p><h2>Eight linked account builds</h2></div><p>Every headline balance can be followed back to an opening balance, activity and closing balance.</p></div><div class="schedule-grid">${Object.entries(d.schedules).map(([k,v])=>schedulePanel(label(k),v)).join('')}</div></section>
    <section class="section" id="evidence"><div class="section-head"><div><p class="eyebrow">Evidence register</p><h2>Source strength and exact location</h2></div><p>External, bank and signed evidence take priority over management spreadsheets and messages.</p></div><div class="evidence-grid">${d.evidence.map(evidenceCard).join('')}</div></section>
    <section class="section"><div class="section-head"><div><p class="eyebrow">Reconciliations</p><h2>Closed bridges, visible caveats</h2></div></div><div class="checks">${d.reconciliations.map(x=>`<article class="check"><span class="pill ${x.status}">${esc(x.status)}</span><strong>${esc(x.name)}</strong><span>${esc(x.calculation)}</span>${x.caveat?`<em>${esc(x.caveat)}</em>`:''}</article>`).join('')}</div></section>
    <section class="section"><div class="grid"><article class="panel"><p class="eyebrow">Uncertainty</p><h2>Items not hidden by the model</h2>${d.uncertainties.map(x=>`<details><summary>${esc(x.issue)} · <span class="pill ${x.confidence}">${esc(x.confidence)}</span></summary><div><strong>${esc(x.range)}</strong><br>${esc(x.impact)}</div></details>`).join('')}</article><article class="panel"><p class="eyebrow">Immediate action</p><h2>Five board controls</h2><ol class="actions">${d.boardRecommendation.actions.map(x=>`<li>${esc(x)}</li>`).join('')}</ol></article></div></section>
    <section class="section" id="decisions"><div class="section-head"><div><p class="eyebrow">Decision register</p><h2>100 evidence-linked certified decisions</h2></div><a href="/review/">Open assessor review →</a></div><div class="table-tools"><label>Search decisions<input id="decision-search" type="search" placeholder="ID, question or treatment"></label><label>Confidence<select id="confidence-filter"><option value="all">All</option><option value="high">High</option><option value="medium">Medium</option><option value="low">Low</option></select></label></div><article class="panel wide"><table class="decision-table" id="decision-table"><thead><tr><th>ID</th><th>Question and evidence locator</th><th>Answer</th><th>Status</th></tr></thead><tbody>${decisionRows(d.decisions)}</tbody></table></article></section>
    <section class="section"><div class="section-head"><div><p class="eyebrow">Individual verification</p><h2>Prepare to explain the judgments</h2></div><p>These prompts support the required no-AI verification exercise.</p></div><div class="grid">${d.verificationPreparation.likelyQuestions.map(q=>`<article class="panel"><span class="source-id">${esc(q.decision)}</span><h3>${esc(q.question)}</h3><p class="subtle">${esc(q.answerGuide)}</p></article>`).join('')}<article class="panel wide scenario"><h3>Changed-fact practice</h3><p><strong>${esc(d.verificationPreparation.changedFactExample.fact)}</strong></p><p>Profit: ${signed(d.verificationPreparation.changedFactExample.profitEffect)} · Cash: ${signed(d.verificationPreparation.changedFactExample.cashEffect)} · ${esc(d.verificationPreparation.changedFactExample.balanceSheetEffect)}</p></article></div></section>`;
  addDecisionFilters();
}

function renderReview(app,d){
  const material=d.decisions.filter(x=>x.reviewTier==='material_judgment'),lows=d.decisions.filter(x=>x.confidence==='low'),disagreements=material.filter(x=>x.agentDisagreement);
  const ready=d.submissionReadiness.ready;
  app.innerHTML=`
    <section class="hero"><div><p class="eyebrow">Assessor view · Version 3 final</p><h1>Judgment, disagreement and certification status.</h1><p class="lede">The model contains 25 material judgments, ${disagreements.length} substantive agent disagreements and ${lows.length} low-confidence decisions.</p></div><aside class="verdict"><small>Submission gate</small><strong>${ready?'Submission ready':'Certified · deployment pending'}</strong><p>${esc(d.student.name)} (${esc(d.student.id)}) certified all 100 decisions on ${esc(d.student.certifiedAt)}.</p></aside></section>
    <section class="metrics"><article class="metric"><span>Total decisions</span><strong>${d.decisions.length}</strong></article><article class="metric"><span>Material judgments</span><strong>${material.length}</strong></article><article class="metric bad"><span>Low confidence</span><strong>${lows.length}</strong></article><article class="metric bad"><span>Agent disagreements</span><strong>${disagreements.length}</strong></article></section>
    <section class="gate"><div><span class="pill ${ready?'closed':'open'}">${ready?'Verified':'Deployment pending'}</span><h2>${ready?'Certification complete':'Remaining publication check'}</h2><p>${esc(d.student.certificationStatement)}</p></div>${d.submissionReadiness.blockingItems.length?`<ul>${d.submissionReadiness.blockingItems.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:`<p><strong>Published:</strong> ${esc(d.publication?.vercel||'Verified')}</p>`}</section>
    <section class="section"><div class="section-head"><div><p class="eyebrow">Revision record</p><h2>Three improvement passes</h2></div></div><div class="iteration-grid">${d.reviewSummary.iterations.map(i=>`<article class="panel"><span class="source-id">Version ${esc(i.version)}</span><h3>Feedback</h3><p>${esc(i.feedback)}</p><h3>Improvement</h3><p class="subtle">${esc(i.improvement)}</p></article>`).join('')}</div></section>
    <section class="section"><div class="section-head"><div><p class="eyebrow">Substantive disagreement</p><h2>Inventory and disposal treatment</h2></div><p>The final base case does not manufacture an adjustment to force agreement.</p></div><div class="grid"><article class="panel"><h3>Agent 1</h3><p>${money(d.reviewSummary.agent1Profit)} profit using the €112,000 inventory roll-forward and a €2,000 disposal provision.</p></article><article class="panel"><h3>Agent 2</h3><p>${money(d.reviewSummary.agent2Profit)} profit using the €121,000 physical valuation and no disposal provision.</p></article><article class="panel wide"><h3>Version 3 base case</h3><p><strong>${money(d.statements.profitAndLoss.netProfit)} profit.</strong> ${esc(d.reviewSummary.baseCaseRationale)} The remaining range is ${esc(d.reviewSummary.profitRange)}.</p></article></div></section>
    <section class="section"><div class="section-head"><div><p class="eyebrow">AI review trail</p><h2>25 material judgments</h2></div><p>Filters identify weak evidence, genuine disagreement and changes from Agent 1.</p></div><div class="filterbar" role="group" aria-label="Decision filters"><button class="active" data-filter="all">All material</button><button data-filter="low">Low confidence</button><button data-filter="disagreement">Agent disagreement</button><button data-filter="changed">Changed from Agent 1</button></div><div class="judgment-list" id="review-list">${material.map(x=>`<article class="judgment" data-confidence="${esc(x.confidence)}" data-disagreement="${x.agentDisagreement?'true':'false'}" data-changed="${x.changedFromAI?'true':'false'}"><header><span class="source-id">${esc(x.id)}</span><span class="pill ${x.confidence}">${esc(x.confidence)}</span><span class="pill closed">Certified</span></header><h3>${esc(x.question)}</h3><div class="judgment-grid"><div><strong>Agent 1 proposal</strong><p>${esc(String(x.aiProposal))}</p></div><div><strong>Independent position</strong><p>${esc(x.independentChallenge)}</p></div><div><strong>Final treatment</strong><p>${esc(String(x.answer))}</p></div><div><strong>Certified reasoning</strong><p>${esc(x.studentReasoning)}</p></div></div><p class="effect">${esc(effect(x.statementEffect))}</p><p class="evidence">${x.evidenceDetails.map(e=>`${esc(e.sourceId)} · ${esc(e.locator)}`).join('<br>')}</p></article>`).join('')}</div></section>
    <section class="section"><div class="grid"><article class="panel"><p class="eyebrow">Uncertainty</p><h2>Items for reviewer attention</h2>${d.uncertainties.map(x=>`<details open><summary>${esc(x.issue)}</summary><div>${esc(x.impact)} <strong>${esc(x.range)}</strong></div></details>`).join('')}</article><article class="panel"><p class="eyebrow">Control checks</p><h2>Reconciliations</h2>${d.reconciliations.map(x=>`<p><span class="pill ${x.status}">${esc(x.status)}</span> <strong>${esc(x.name)}</strong><br><span class="subtle">${esc(x.calculation)}</span>${x.caveat?`<br><em>${esc(x.caveat)}</em>`:''}</p>`).join('')}</article></div></section>`;
  document.querySelectorAll('[data-filter]').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('[data-filter]').forEach(b=>b.classList.toggle('active',b===btn));document.querySelectorAll('#review-list .judgment').forEach(card=>{const f=btn.dataset.filter;card.hidden=!(f==='all'||(f==='low'&&card.dataset.confidence==='low')||(f==='disagreement'&&card.dataset.disagreement==='true')||(f==='changed'&&card.dataset.changed==='true'))})}));
}
load();
